### ISSUE TITLE
Question: Project vision

### ISSUE THREAD

**Issue by JesusLeon** [amaya382/anyrc#12]
Hi,

you have a nice project working here. Thanks for your work! 

I'm wondering what is your project "vision" in terms of maintenance and longevity? By this i mean, do you intend to keep it up to date for as long as you can or is it just a temporary project that can be abandoned at any time?

I ask because i used to use a similar tool called **sshrc** (which you actually refer to in the readme) which was suddenly abandoned and the account even removed, and this let many users with an outdated/broken tool.

Thank you!

**Comment by amaya382** [comment]
Hi, @JesusLeon 

Actually, I use this project myself in https://github.com/amaya382/dotfiles every day.
I'm planning to keep this project updating as well as possible. I make sure nothing like sshrc happens.
Of course, contribs from anyone are welcome :)
